#!/usr/bin/env python3

import glob
import os
import sys
import yaml

def get_def(fname):
    with open(fname) as f:
        t=f.read()
    d=yaml.load(t)
    return d['def']


def get_default_args():
    dir = '.'
    if os.getcwd() == os.path.dirname(os.path.realpath(sys.argv[0])):
        dir = '..'
    return glob.glob(dir + '/*.yaml')


if len(sys.argv) > 1:
    args = sys.argv[1:]
else:
    args = get_default_args()

for fn in args:
    defn = get_def(fn)
    print(defn)
